# Generated by Django 4.1.2 on 2022-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20221023_1347"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(max_length=500)),
                (
                    "facebook",
                    models.CharField(
                        default="https://www.facebook.com/", max_length=500
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        default="https://www.instagram.com/", max_length=500
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        default="https://www.twitter.com/", max_length=500
                    ),
                ),
                ("shipping_cost", models.FloatField(default=50.0)),
            ],
        ),
        migrations.DeleteModel(name="Frontpage",),
    ]
