# Generated by Django 4.1.2 on 2022-10-23 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_auto_20221023_1347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 23, 15, 3, 53, 575359)
            ),
        ),
    ]
