# Generated by Django 4.1.2 on 2022-10-23 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 23, 15, 4, 6, 903743)
            ),
        ),
    ]
