# Generated by Django 4.1.2 on 2022-10-23 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 23, 16, 10, 25, 539668)
            ),
        ),
    ]
