# Generated by Django 4.1.2 on 2022-10-30 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 30, 14, 18, 24, 705262)
            ),
        ),
    ]
