# Generated by Django 4.1.2 on 2022-11-06 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 16, 51, 93263)),
        ),
    ]
