# Generated by Django 4.1.2 on 2022-12-15 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_product_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 15, 22, 55, 39, 733341)
            ),
        ),
    ]
