# Generated by Django 4.1.2 on 2022-12-15 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_product_active_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 15, 22, 56, 13, 292058)
            ),
        ),
    ]
