# Generated by Django 4.1.2 on 2022-12-15 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_product_active_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 16, 0, 58, 33, 452379)
            ),
        ),
    ]
