# Generated by Django 4.1.2 on 2022-12-23 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_product_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 23, 16, 28, 6, 368571)
            ),
        ),
    ]
