# Generated by Django 4.1.2 on 2023-03-03 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 21, 53, 9, 240009)),
        ),
    ]
