# Generated by Django 4.1.2 on 2023-03-03 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 23, 44, 10, 345704)),
        ),
    ]
