# Generated by Django 4.1.2 on 2022-10-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="first_name",),
        migrations.RemoveField(model_name="order", name="last_name",),
        migrations.RemoveField(model_name="order", name="place",),
        migrations.RemoveField(model_name="order", name="zipcode",),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Mysuru", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order", name="address", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order", name="email", field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order", name="phone", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
