# Generated by Django 4.1.2 on 2022-10-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_first_name_remove_order_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_info",
            field=models.CharField(default="COD", max_length=255),
        ),
        migrations.AlterField(
            model_name="order", name="address", field=models.CharField(max_length=1000),
        ),
    ]
