# Generated by Django 4.1.2 on 2022-11-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_info_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='COD', max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(default='COD', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(default='COD', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=254),
        ),
    ]
