# Generated by Django 4.1.2 on 2023-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_paid_amount_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='longtitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
    ]
