# Generated by Django 4.1.2 on 2023-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_latitude_order_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='longtitude',
            field=models.CharField(default='', max_length=255),
        ),
    ]
