# Generated by Django 4.1.2 on 2023-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_latitude_alter_order_longtitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(default='', max_length=255),
        ),
    ]
